services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=server.py
      - FLASK_RUN_HOST=0.0.0.0

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"